### ISSUE TITLE
Download genomes based on accession number

### ISSUE THREAD

**Issue by dparks1134** [kblin/ncbi-genome-download#119]
Hi, 

Thank you for putting this script together. I have a feature request. Would it be possible to add in a flag to allow only genomes specified by their NCBI accession numbers (e.g., GCF_000008865.2 or GCA_000008865.2) to be downloaded. Ideally, these accession numbers would be read from an input file or provided directly on the command line. 

I am a maintainer of the GTDB (http://gtdb.ecogenomic.org) and my hope is to direct GTDB users to your script as a way to download large numbers of genomes from NCBI. The challenge is that the GTDB indexes genomes by their accession number.

I'll also second having a formal way to cite this script/repository (e.g., Zenodo) since I suspect many people will find this useful and it would be great to have a strong incentive to maintain this script. :)

Cheers,
Donovan

**Comment by kblin** [comment]
Hi there. I notice a description of that parameter is missing from the README file, but the `--assembly-accessions` / `-A` parameter does just what you need.
Note that you can't mix GenBank `GCA_....` and RefSeq `GCF_....` accessions for now, because you need to decide if you want to download from RefSeq or GenBank.

**Comment by kblin** [comment]
Oh, just in case that's not clear from the `--help` text, you can pass a filename that contains one accession per line to the `--assembly-accession` parameter.

**Comment by dparks1134** [comment]
Brilliant! Thanks.
