### ISSUE TITLE
No downloads matched your filter

### ISSUE THREAD

**Issue by nahid18** [kblin/ncbi-genome-download#129]
Hi, I am trying to download viral genome from NCBI. 
**Almendravirus is a genus of RNA viruses.**
This genus has 10 genomes in the NCBI database.

Here's my code:

`import ncbi_genome_download as ngd`
`ngd.download(section='refseq', 
           file_formats='fasta,rna-fasta,rna-fna', 
           genera='Almendravirus',
           output='out',
           groups='viral')`

It returns `No downloads matched your filter. Please check your options.`

I don't understand what am I missing here. 
Can you kindly check and help?

**Comment by kblin** [comment]
The `genera` parameter relies on the `genus` field in the NCBI `assembly_summary.txt` file on their download server. If that field doesn't start with the string you're searching for, the record doesn't match. No single entry in the viral assembly summary has a genus of `Almendravirus`. That's because viral naming doesn't really fit into the binary taxonomy of living organisms, and they're named things like "Balsa almendravirus" or the like.

You have two options to proceed: you can try the fuzzy matching for the genus, which will search for your term existing anywhere in the genus field (I'm running the command line tool, but the API will work as well):

```
❯ ngd --fuzzy-genus --genera "Almendravirus" --dry-run viral
Considering the following 4 assemblies for download:
GCF_000927335.1	Arboretum almendravirus	Lo-121
GCF_002815515.1	Balsa almendravirus	CoB 76
GCF_002366165.1	Coot Bay almendravirus	EVG5-53
GCF_002366105.1	Rio Chico almendravirus	GAM 195
```

Or you can try to use the `gimme_taxa.py` contributed script that we also ship with `ncbi-genome-download` to query the NCBI taxonomy database for taxids and then use those to download by taxid:

```
❯ gimme_taxa.py -j Almendravirus > almendravirus.txt
❯ ngd --taxids almendravirus.txt --dry-run viral
Considering the following 5 assemblies for download:
GCF_000927335.1	Arboretum almendravirus	Lo-121
GCF_002815515.1	Balsa almendravirus	CoB 76
GCF_002366165.1	Coot Bay almendravirus	EVG5-53
GCF_000926695.1	Puerto Almendras virus	LO-39
GCF_002366105.1	Rio Chico almendravirus	GAM 195
```
Note that this will get one sequence the fuzzy option didn't catch because apparently `GCF_000926695.1` is called `Puerto Almendras virus`, and doesn't contain `almendravirus` in the genus field.

**Comment by nahid18** [comment]
Thank you for your detailed answer. So I can see, it's better to run the command with Species name. 
Does this tool have download option with only species name?

For example, instead of the genera option in the command below:
`ngd.download(section='refseq', file_formats='fasta,rna-fasta,rna-fna', genera='Almendravirus', output='out', groups='viral')`

can I use **only species name** such as **Balsa almendravirus** or **Puerto Almendras virus** to download the genome files?
If so, can you give me an example code?

**Comment by kblin** [comment]
The `--genera` field is a bit of a lie, because the NCBI doesn't really provide genus/species separately. So while you can use this for e.g. bacteria to grab all entries where the species name starts with e.g. "Bacillus", thus providing a genus-level filter, that's not how it really works.

You can just put a full string in and it'll work. E.g.
`ngd.download(section='refseq', file_formats='fasta,rna-fasta,rna-fna', genera='Balsa almendravirus,Puerto Almendras virus', output='out', groups='viral')` should work.

**Comment by nahid18** [comment]
Amazing! It worked as intended. Thanks a lot for your kind help.
