### ISSUE TITLE
Allow creation of --human-readable hierarchy if files are already downloaded

### ISSUE THREAD

**Issue by kblin** [kblin/ncbi-genome-download#16]
Currently the links in the `human_readable` folder are just created for records that are downloaded while `ncbi-genome-download` is being called with `--human-readable`. If a file is already up-to-date with a good checksum match from a previous run without `--human-readable`, no link will be created.

The logic should be changed to allow for a run with `--human-readable` to create links for already downloaded files as well.

**Comment by joshbaldwin** [comment]
Hey kblin,

I started working on this.  I didn't say anything because this is my first time with python and submitting on github, so I was not sure how long it was going to take me.  I have a solution that works that you can see here: https://github.com/joshbaldwin/ncbi-genome-download/tree/issue16

I tested this by downloading a file with the tool, then running the same command again but with the --human-readable flag to see the symbolic link gets created.

Example:
$ncbi-genome-download --section genbank --genus Absidia fungi
$ncbi-genome-download --section genbank --genus Absidia --human-readable fungi

If you want this, I can submit it.  Otherwise, I would like to do a little bit of refactoring/rethinking since it does appear to create some duplicate logic.  Let me know if you have any other thoughts since like I said, this is my first time with python :)

**Comment by kblin** [comment]
I'll have a look at this after the weekend, I'm a bit busy right now. But if you have a good idea how to avoid logic duplication there, that'd also be fine.

**Comment by kblin** [comment]
Implemented by 41e4562123bbe7da2db9932675f4b276696dd4e4.
