### ISSUE TITLE
doanload failed when groups is set to all

### ISSUE THREAD

**Issue by showteeth** [kblin/ncbi-genome-download#175]
When I download genome with: `ncbi-genome-download --species-taxids 562 all`, I got nothing.
When I download genome with: `ncbi-genome-download --species-taxids 562 bacteria`, I got what I wanted.
I wonder why there is such a difference? In my understanding, these two commands should get the same result.

**Comment by kblin** [comment]
Ah, that was a fun one to find. The issue is that RefSeq doesn't have a metagenome database, and we have logic to error out when you explicitly ask for `ncbi-genome-download metagenomes` (as a contrast `ncbi-genome-download --section genbank metagenomes` works), but the `all` logic didn't take that into account.

**Comment by kblin** [comment]
I'll release a new version of `ncbi-genome-download` with a fix on Monday, I don't have easy access to my release signing key right now.

**Comment by showteeth** [comment]
Thank you for your timely reply and look forward to new version!

**Comment by showteeth** [comment]
Sorry to interrupt, but did you forget to release a new version of `ncbi-genome-download`?

**Comment by kblin** [comment]
Yeah, I got distracted. But 0.3.1 is released now and should be on pypi already.
