### ISSUE TITLE
No downloads matched error

### ISSUE THREAD

**Issue by tasha99** [kblin/ncbi-genome-download#219]
Hello, I'm trying to download the entire Pseudomonas syringae species group fasta files. Im using the taxonomy ID 136849 but it keeos saying that there are no downloads that match this filter. The exact code I'm using is this:

ncbi-genome-download --formats fasta --species-taxid 136849 bacteria 

Any idea how to overcome this issue?
TIA

**Comment by kblin** [comment]
If I read the NCBI taxonomy database correctly. `136849` is a species group, not a species, so that likely won't be exposed in the dataset `ncbi-genome-download` is reading to calculate which files to download, namely the `assembly_summary.txt` file.
My suggestion would be to use the `gimme_taxa.py` script for the `contrib` directory to grab a list of descendant taxids that `ncbi-genome-download` then does know how to download.

**Comment by kblin** [comment]
Closing stale question
