### ISSUE TITLE
Add --acc id for download specific genomes

### ISSUE THREAD

**Issue by Sanrrone** [kblin/ncbi-genome-download#40]
Dear, will be very usefull to fetch an specific genomes only with acc id, I think in a file with several ID's or looping each one.

Regards

**Comment by kblin** [comment]
I'm afraid the NCBI accession is not available to `ncbi-genome-download` at this point in time. `ncbi-genome-download` only knows what is in the `assembly_summary.txt` file on the FTP server, and the accession ID is not part of that as far as I can see.

**Comment by kblin** [comment]
While this is out of scope for this project, try 
[get_from_ncbi.py.txt](https://github.com/kblin/ncbi-genome-download/files/1033238/get_from_ncbi.py.txt)
to download GenBank files.

You might want to rename the file to remove the `.txt` ending, I just had to add that because GitHub doesn't allow uploading python scripts directly

**Comment by Sanrrone** [comment]
Thanks mr kblin, the script works perfect.
