### ISSUE TITLE
Downloads stall in mid-process

### ISSUE THREAD

**Issue by kblin** [kblin/ncbi-genome-download#50]
To quote @forestdussault from issue #19 

> Just came across your script today - nice work. Unfortunately it is hanging for me with the following command:
> 
> `ncbi-genome-download --assembly-level complete --format fasta --human-readable --verbose --debug bacteria`
> 
> The downloader will progress for a few minutes and then stop. It seems to stop while attempting to start a new HTTPS connection:
> 
> ```
> DEBUG: Skipping entry with assembly level 'Contig'
> INFO: Downloading record 'GCF_000465235.1'
> INFO: Starting new HTTPS connection (1): ftp.ncbi.nlm.nih.gov
> ```

**Comment by kblin** [comment]
Off-hand, I have multiple ideas on what could be causing this, and none of them should be directly `ncbi-genome-download`'s fault :wink:

Where on this planet are you, and how good is your connection to the NCBI usually?

Do you have a proxy server sitting between you and the internet?

**Comment by forestdussault** [comment]
I'm in Ontario, Canada - and I'm not too sure about my workplace internet setup. I actually ended up writing my own (very sloppy) script to do the download before I saw your reply. I was able to download everything fine by making system calls to curl with NCBI FTP links pulled from the assembly summary file.

I skimmed through your source code and can't figure out why it would be failing.

**Comment by kblin** [comment]
The main difference here is using FTP with curl and HTTPS in ncbi-genome-download, which I picked mainly due to the absolutely horrendous API python has for FTP.
Chances are that NCBI just had some server issues and by the time you re-tried the download those were fixed.
Maybe you have an opportunity to retry  ncbi-genome-download in the future and see if this happens again.

**Comment by kblin** [comment]
I'm assuming this was a transient issue on the NCBI side and closing this issue. Please feel free to reopen if this happens again and looks like to be caused by `ncbi-genome-download` after all.

**Comment by elzerac** [comment]
Hello, I am experiencing this issue, but the download is not initalizing giving the following error `ERROR: Download from NCBI failed: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='ftp.ncbi.nih.gov', port=443): Max retries exceeded with url: /genomes/refseq/bacteria/assembly_summary.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2ad363a3dd68>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)`

It looks like it cannot even access the assembly)summary file. From reading a little bit on NCBI they state "These two paths are equivalent hence they do currently provide the same content, however, ftp://ftp.ncbi.nlm.nih.gov/ is the preferred path and the abbreviated path, ftp://ftp.ncbi.nih.gov/, may not be supported indefinitely." Perhaps we should switch the path to ftp://ftp.ncbi.nlm.nih.gov/ ? Could this be the issue?

**Comment by SergeyBaikal** [comment]
cbi-genome-download all -s refseq --formats fasta --parallel 10 -P --flat-output -o /media/sf_Shared_folders/RefSeq_All_v217_2023/download/
ERROR: Download from NCBI failed: ProxyError(MaxRetryError('None: Max retries exceeded with url: /genomes/all/GCF/006/347/935/GCF_006347935.1_ASM634793v1/md5checksums.txt (Caused by None)'))
