### ISSUE TITLE
The script is not at all a necessary tool

### ISSUE THREAD

**Issue by UddalakMitra** [kblin/ncbi-genome-download#85]
This script is not at all necessary tool for downloading species genomes from NCBI. Moreover, it cannot parse most of the critical queries. NCBI itself provides an efficient and excellent tools https://www.ncbi.nlm.nih.gov/assembly/ to download multiple genomes and with extremely vast utilities.

**Comment by jrjhealey** [comment]
Wow. Is this a useful comment? If you don't like or need the tool, you don't need to use it...the 200+ people that have starred the repository would beg to differ.

**Comment by kblin** [comment]
You are absolutely correct that this tool is not necessary for downloading genomes from the NCBI. However, for the people who are using the tool, it seems to be doing the job just fine. I wrote it because it covers a use-case that e.g. [the NCBI Assebly download service](https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/#downloadservice) does not cover (like being automatable for large-scale downloads). In fact, if you look at the next point in the FAQ, the NCBI itself suggests using their HTTPS server to download large datasets. `ncbi-genome-download` does just that, with a bit of added convenience functions on top to figure out which files to download. But of course as @jrjhealey said, if you don't like it, you don't have to use it.

I'm closing this report, because there's nothing concrete to work with as to what "critical queries" the tool can not "parse". Feel free to re-open if you have a concrete use case that you think should be supported but isn't.
